buildscript {
	repositories {
		mavenCentral()
	}
	dependencies {
		classpath "com.mobidevelop.robovm:robovm-gradle-plugin:$roboVMVersion"
	}
}
apply plugin: "java-library"
apply plugin: "robovm"
[compileJava, compileTestJava]*.options*.encoding = 'UTF-8'
sourceCompatibility = '1.7'

ext {
	mainClassName = "com.teenagemutantninjacoders.robotwarehouse.IOSLauncher"
}

launchIPhoneSimulator.dependsOn build
launchIPadSimulator.dependsOn build
launchIOSDevice.dependsOn build
createIPA.dependsOn build

robovm {
	archs = "arm64"
}

eclipse.project.name = appName + "-ios"
dependencies {
	implementation project(":core")
	api "com.mobidevelop.robovm:robovm-rt:$roboVMVersion"
	api "com.mobidevelop.robovm:robovm-cocoatouch:$roboVMVersion"
	api "com.badlogicgames.gdx:gdx-backend-robovm:$gdxVersion"
	api "com.badlogicgames.gdx:gdx-platform:$gdxVersion:natives-ios"
}