app.version=1.0
app.id=com.teenagemutantninjacoders.robotwarehouse
app.mainclass=com.teenagemutantninjacoders.robotwarehouse.IOSLauncher
app.executable=IOSLauncher
app.build=1
app.name=RobotWarehouse
